#!/bin/bash
#PBS -S /bin/bash

# Put here the requests for the desired hardware
# number of nodes (nodes), cores per node (ppn), maximum time of execution (HH:MM:SS) queue (name_of_the_queue)

#PBS -l nodes=1:ppn=1,walltime=390:00:00 -q cerbero

# Set the job name
#PBS -N biot 

# Set the output file and merge it to the sterr
#PBS -o out-hostname-XyZ-N1x1-qsub.txt
#PBS -j oe
#PBS -e out-hostname-XyZ-N1x1.txt

# Start the job in the current directory (PBS starts in the home folder)
cd ${PBS_O_WORKDIR}

#---------------------------------------------------------------------#
# Now run the executable
# Nella riga successiva si deve scrivere il/i comando/i di lancio
# completo di redirezione di input e/o output se necessario
# YOUR LAUNCH COMMAND BELOW completed with I/O redirection if needed

source ./configure.sh

make > crb_cmp_log && ./por3d1d -f single_rod_thins.pot > crb_out 2>&1

#source tester.sh > gigat_output 2>&1

#---------------------------------------------------------------------#

date
